module.exports = {
  AUTH_SET_TOKEN: "SET_TOKEN",
  AUTH_DISCARD_TOKEN: "DISCARD_TOKEN",
  AUTH_SET_USER: "SET_USER",
  GET_ERRORS: "GET_ERRORS",
  SET_CURRENT_USER: "SET_CURRENT_USER",
  GET_CURRENT_USER: "GET_CURRENT_USER",
  GET_USER_DATA: "GET_USER_DATA",
  GET_USER: "GET_USER",
  ADD_DATA_SUCCESS: "ADD_DATA_SUCCESS",
  GET_EMAIL_DATA: "GET_EMAIL_DATA"
};
